#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
#ifndef CPAYSDK_SWIFT_H
#define CPAYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CPaySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC7CPaySDK15CPayBillingAddr")
@interface CPayBillingAddr : NSObject
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable street2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckData;

SWIFT_CLASS("_TtC7CPaySDK9CPayCheck")
@interface CPayCheck : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable app;
@property (nonatomic, strong) CPayCheckData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckDataPayment;

SWIFT_CLASS("_TtCC7CPaySDK9CPayCheck13CPayCheckData")
@interface CPayCheckData : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable object;
@property (nonatomic) NSInteger amount;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger timeCanceled;
@property (nonatomic, copy) NSString * _Nullable expiry;
@property (nonatomic) NSInteger timeCreated;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) NSInteger amountCaptured;
@property (nonatomic) NSInteger amountRefunded;
@property (nonatomic) NSInteger timeCaptured;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, strong) CPayCheckDataPayment * _Nullable payment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckDataPaymentData;

SWIFT_CLASS("_TtCCC7CPaySDK9CPayCheck13CPayCheckData20CPayCheckDataPayment")
@interface CPayCheckDataPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) CPayCheckDataPaymentData * _Nullable data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCCC7CPaySDK9CPayCheck13CPayCheckData20CPayCheckDataPayment24CPayCheckDataPaymentData")
@interface CPayCheckDataPaymentData : NSObject
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK12CPayConsumer")
@interface CPayConsumer : NSObject
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CPayENVMode, open) {
  CPayENVModeDEV = 0,
  CPayENVModeQA = 1,
  CPayENVModeUAT = 2,
  CPayENVModePROD = 3,
};

@class CPayExtTransaction;
@class CPayExtDevice;

SWIFT_CLASS("_TtC7CPaySDK7CPayExt")
@interface CPayExt : NSObject
@property (nonatomic, strong) CPayExtTransaction * _Nullable transaction;
@property (nonatomic, strong) CPayExtDevice * _Nullable device;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK13CPayExtDevice")
@interface CPayExtDevice : NSObject
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable os;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtTransactionReceipt;

SWIFT_CLASS("_TtC7CPaySDK18CPayExtTransaction")
@interface CPayExtTransaction : NSObject
@property (nonatomic, strong) CPayExtTransactionReceipt * _Nullable receipt;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK25CPayExtTransactionReceipt")
@interface CPayExtTransactionReceipt : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayProduct;
@class CPayShipping;

SWIFT_CLASS("_TtC7CPaySDK9CPayGoods")
@interface CPayGoods : NSObject
@property (nonatomic, copy) NSArray<CPayProduct *> * _Nullable goods;
@property (nonatomic, strong) CPayShipping * _Nullable shipping;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK16CPayInstallments")
@interface CPayInstallments : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable paymentNumber;
@property (nonatomic, copy) NSString * _Nullable quantity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayRequest;
@class CPayResult;
@class UIOpenURLContext;
@class UIApplication;
@class NSURL;
@class NSUserActivity;

SWIFT_CLASS("_TtC7CPaySDK11CPayManager")
@interface CPayManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (CPayManager * _Nonnull)sharedInst SWIFT_WARN_UNUSED_RESULT;
/// Used to set the runtime environment. See @CPayENVMode
/// \param mode An enumeration variable of CPayENVMode.
///
///
/// returns:
/// true if successful.
- (BOOL)setMode:(enum CPayENVMode)mode SWIFT_WARN_UNUSED_RESULT;
/// Set up an access token for accessing the API.
/// \param token Generated by Citcon.
///
///
/// returns:
/// true if successful.
- (BOOL)setAccessToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
/// Request an order to complete payment.
/// \param order An instance of the CPayRequest class. See @CPayRequest.
///
/// \param callback A callback function of type @CPayRequestCallback. It will be called when payment is complete.
///
///
/// returns:
/// true if the call was successful, but does not mean the payment has been made. It depends on the callback.
- (BOOL)requestOrder:(CPayRequest * _Nonnull)order callback:(void (^ _Nonnull)(CPayResult * _Nullable))callback SWIFT_WARN_UNUSED_RESULT;
/// Query information about an order.
/// \param transId Specifies the id of the order.
///
/// \param callback A callback function of type @CPayCheckCallback. It will be called when query is complete.
///
///
/// returns:
/// true if the call was successful, but does not mean the query has completed. It depends on the callback.
- (BOOL)inquireOrder:(NSString * _Nonnull)transId callback:(void (^ _Nonnull)(CPayCheck * _Nullable))callback SWIFT_WARN_UNUSED_RESULT;
/// Get the version of the SDK.
///
/// returns:
/// SDK version.
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// It is called in the delegate method scene:openURLContexts of SceneDelegate.
/// note:
/// UPOP crashes because UIAlert is used in iOS target iOS 13.
/// \param URLContexts Instance of class NSSet passed by SceneDelegate.
///
///
/// returns:
/// true if the call was successful, but does not mean the query has completed. It depends on the callback.
- (void)handleScene:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
/// It is called in the delegate method application:openURL:options of AppDelegate.
/// \param app Instance of class UIApplication passed by AppDelegate.
///
/// \param url Instance of class URL passed by AppDelegate.
///
/// \param options Instance of class NSDictionary passed by AppDelegate.
///
///
/// returns:
/// false.
- (BOOL)handleUrl:(UIApplication * _Nonnull)app open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// If WeChat payment is used, it is called in the delegate method application:continueUserActivity:restorationHandler of AppDelegate.
/// Or it is called in the delegate method scene:continueUserActivity of SceneDelegate.
/// \param userActivity Instance of class NSUserActivity passed by AppDelegate.
///
///
/// returns:
/// Void
- (void)handleUniversalLink:(NSUserActivity * _Nonnull)userActivity;
/// Get an access token signed by Citcon.
/// <ul>
///   <li>
///     Note This function only used by test. Will remove in official realse.
///   </li>
/// </ul>
/// \param callback The callback function will be called after get access token
///
///
/// returns:
/// Void
- (void)getAccessToken:(NSString * _Nonnull)vendor onComplete:(void (^ _Nonnull)(NSString * _Nullable))callback;
/// Generate an order for test
/// \param order An instance of CPayRequest.
///
/// \param callback A callback function of type @CPayRequestCallback. It will be called when payment is complete.
///
///
/// returns:
/// Void
- (void)generateOrder:(CPayRequest * _Nonnull)order callback:(void (^ _Nonnull)(CPayResult * _Nullable))callback;
@end

@class CPayPaymentData;

SWIFT_CLASS("_TtC7CPaySDK11CPayPayment")
@interface CPayPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable indicator;
@property (nonatomic) BOOL requestToken;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable client;
@property (nonatomic) NSInteger expiry;
@property (nonatomic, copy) NSString * _Nullable format;
@property (nonatomic, strong) CPayPaymentData * _Nullable data;
@property (nonatomic, strong) CPayBillingAddr * _Nullable billingAddress;
@property (nonatomic, copy) NSString * _Nullable nonce;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK15CPayPaymentData")
@interface CPayPaymentData : NSObject
@property (nonatomic, copy) NSString * _Nullable issuer;
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK11CPayProduct")
@interface CPayProduct : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic) int32_t quantity;
@property (nonatomic) int32_t totalAmount;
@property (nonatomic) int32_t unitAmount;
@property (nonatomic) int32_t totalTaxRate;
@property (nonatomic) int32_t totalTaxAmount;
@property (nonatomic) int32_t totalDiscountAmount;
@property (nonatomic) int32_t taxableAmount;
@property (nonatomic) int32_t taxExemptAmount;
@property (nonatomic, copy) NSString * _Nullable totalDiscountCode;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic, copy) NSString * _Nullable desc;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayTranscation;
@class CPayUrls;
@class UIViewController;

SWIFT_CLASS("_TtC7CPaySDK11CPayRequest")
@interface CPayRequest : NSObject
@property (nonatomic, strong) CPayTranscation * _Nonnull transaction;
@property (nonatomic, strong) CPayConsumer * _Nullable consumer;
@property (nonatomic, strong) CPayPayment * _Nullable payment;
@property (nonatomic, strong) CPayGoods * _Nullable goods;
@property (nonatomic, strong) CPayInstallments * _Nullable installments;
@property (nonatomic, strong) CPayUrls * _Nonnull urls;
@property (nonatomic, strong) CPayExt * _Nullable ext;
@property (nonatomic, copy) NSString * _Nullable scheme;
@property (nonatomic, copy) NSString * _Nullable universalLink;
@property (nonatomic) BOOL request3DSecureVerification;
@property (nonatomic, strong) UIViewController * _Nullable controller;
@property (nonatomic, copy) NSString * _Nullable unionpayMode;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayResultData;

SWIFT_CLASS("_TtC7CPaySDK10CPayResult")
@interface CPayResult : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, strong) CPayResultData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayResultPayment;

SWIFT_CLASS("_TtCC7CPaySDK10CPayResult14CPayResultData")
@interface CPayResultData : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable object;
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) NSInteger amount;
@property (nonatomic) NSInteger amountCaptured;
@property (nonatomic) NSInteger amountRefunded;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger timeCreated;
@property (nonatomic) NSInteger timeAuthorized;
@property (nonatomic) NSInteger timeCaptured;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
@property (nonatomic, strong) CPayResultPayment * _Nullable payment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC7CPaySDK10CPayResult14CPayResultData17CPayResultPayment")
@interface CPayResultPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK15CPayRuntimeInst")
@interface CPayRuntimeInst : NSObject
+ (NSString * _Nonnull)NTFY_ASYNC SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK12CPayShipping")
@interface CPayShipping : NSObject
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable street2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK15CPayTranscation")
@interface CPayTranscation : NSObject
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) int32_t amount;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, copy) NSString * _Nullable note;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7CPaySDK8CPayUrls")
@interface CPayUrls : NSObject
@property (nonatomic, copy) NSString * _Nullable ipn;
@property (nonatomic, copy) NSString * _Nullable success;
@property (nonatomic, copy) NSString * _Nullable cancel;
@property (nonatomic, copy) NSString * _Nullable fail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
